name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # 毎日 09:00 JST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install snk
        run: npm install -g snk

      - name: Generate SVG
        run: snk generate --theme dark

      - name: Commit svg
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add snk.svg
          git commit -m "chore: update snake" || echo "No changes"
          git push
