name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *" # 毎日 09:00 JST (UTC 00:00)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: yamada-michel27
          BRANCH_NAME: main
          UTC_OFFSET: 9
          THEME: gruvbox
          OUTPUT_DIR: profile-summary-card-output
